//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LargeBank.API
{
    using System;
    using System.Collections.Generic;
    using Models;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Statements = new HashSet<Statement>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int AccountID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Balance { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statement> Statements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }

        internal void Update(AccountsModel account)
        {
            throw new NotImplementedException();
        }
    }
}
